### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by vyv03354** [onihusube/blog#16]
「CC-BY 4.0の下でのパブリックドメイン」というのが意味不明でどういう条件で使えるのかよくわからないので、文言を変更していただけないでしょうか。「CC-BY 4.0」か「パブリックドメイン」のどちらか片方ということはあっても、両方同時ということはありえません。付帯するクリエイティブ・コモンズのロゴ画像はtitle属性が"CC-BY 4.0"でalt属性が"CC0"となっており、さらに意味不明です。

もしかして誰もライセンスなんか見ていないことを証明するなどの目的でわざとやっていますか?

**Comment by onihusube** [comment]
ご指摘はごもっともで、きちんと理解しないまま指定していました。意図としてはCC-BY 4.0だったので、クリエイティブコモンズという文言を削除しました。

ただ、

> もしかして誰もライセンスなんか見ていないことを証明するなどの目的でわざとやっていますか?

この一文は余計で、害意が高すぎると思います。指摘の内容が正当でもこうした余計な一言が含まれているとその正当性を失ってしまうと思うので、以後気を付けていただけたらと思います。
